<?php
$CONFIG = array (
  'instanceid' => 'ocwm7nb9v1ru',
  'passwordsalt' => '7txRA4EavVO05xpffOvcCaTORDIUqq',
  'secret' => 'n1d/Q1QDjy69g3R7FoUYmxwsM86EwQbuCzwWPbcGpPyIRtUv',
  'trusted_domains' => 
  array (
    0 => 'peneh.com',
    1 => 'e.peneh.com',
    2 => 'files.peneh.com',
  ),
  'datadirectory' => '/homepages/19/d818264003/htdocs/files/data',
  'dbtype' => 'mysql',
  'version' => '23.0.2.1',
  'overwrite.cli.url' => 'https://peneh.com/',
  'dbname' => 'dbs5557918',
  'dbhost' => 'db5006716635.hosting-data.io',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'dbu48095',
  'dbpassword' => '29Kasirer,',
  'installed' => true,
  'htaccess.RewriteBase' => '/',
  'simpleSignUpLink.shown' => false,
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'pipe',
  'mail_from_address' => 'support',
  'mail_domain' => 'peneh.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'yoely@peneh.com',
  'mail_smtppassword' => 'upwrbpyujvxlakhj',
  'mail_smtpsecure' => 'tls',
  'maintenance' => false,
);
